### ISSUE TITLE
Create "Final R Code"

### ISSUE THREAD

**Issue by ismailsunni** [ismailsunni/MasterThesis#10]
Create how will the final R code be to run the benchmark and run the test. Ideally as simple as possible

**Comment by ismailsunni** [comment]
To run a benchmark across different docker container, it would be something like this:
```R
benchmarks(code_or_r_script_path, list_of_r_implementations, list_of_platform, ... )
```
The `...` parameter will be passed to the `microbenchmark` function.

Then to run a package's test in R implementation and platform 
```R
test(r_implementation, platform, ...)  # used in testing a directory 
```
The `...` parameter will be passed to the `devtools:test` function.

The behavior would be mounting the working directory to the docker container `/home/docker`

I will need to think how the external data access. For example, if the data is not under the current working directory. It will be tricky to access the data.

**Comment by nuest** [comment]
This is a good start. Could you add a few more details to the parameters, e.g., what input type is accepted and how you imagine the inputs to look like. Ideally, these are based on existing standards or specs, and have reasonable defaults - what are reasonable defaults?

Also, have functions that provide a list of all supported implementations and platforms, and give them both human readable and unique names, e.g. with a named list (`list(debian = "Debian Linux", centos = "CentOS Linux")` ?)

```R
altrnative::benchmarks(code = expression("1 + 1"))

altrnative::benchmarks(code = expression("read.file('data.csv')"), expression("source('myScript.R')"))

altrnative::benchmarks(code = "myScript.R", impl = s("base-r", "fastr"), platform = c("centos", "debian"))

altrnative::benchmarks(code = c("myScript.R", "directory/secondScript.R"),
    impl = "base-r",
    platform = c("redhat", sessionInfo()$R.version$platform))

altrnative::benchmarks(code = c(expression("install.packages('xyz')", expression("library(xyz)"), expression("xyz::run()")),
    impl = altrnative::implementations()[2:4],
    platform = altrnative::platforms()[1:2])

# Please take a look at these, maybe you don't need altrnative::platforms()
rhub::platforms()$name
str(rhub::platforms())
```

It is also great that you think about the mounting and the working directory. IMO the option you present above should suffice for your thesis. _Don't worry about data outside of the current working directory!_ That really seems to be an edge case. Instead, in your own code, always use `here::here(..)` to load data relative to the current project, and you should be fine.

_Next_, think about the returned output. The output needs a reasonable data structure (something list-like) to access the results of `list_of_impls * list_of_platform`-many container runs!

------

I strongly suggest you put your functions in a little R package. It just makes things a lot easier to develop for yourself, and easier for others to try out (clean dependency management, versioning, documentation, etc.). `pkgKitten::kitten("..")` might help you get started. My package name suggestion: `altRnative` :smile:
Looking forward to hear your ideas, `available::available("yourIdea")` helps with that.

**Comment by ismailsunni** [comment]
> Also, have functions that provide a list of all supported implementations and platforms, and give them both human readable and unique names, e.g. with a named list (list(debian = "Debian Linux", centos = "CentOS Linux") ?)
Yes, I plan to do that to make it easy for the user to know which one is supported. Below is the list of the supported implementations and platforms, including their default. The supported platform takes from here https://github.com/r-hub/sysreqsdb/tree/master/platforms
```R
supported_platforms = list(
    'debian' = 'Debian Linux',  # default
    'fedora' = 'Fedora',
   'arch' = 'Arch Linux',
   'ubuntu' = 'Ubuntu',
   'centos6' = 'CentOS Linux'
)
supported_implementations = list (
    'gnur' = 'GNU R',  # default
    'mro' = 'Microsoft Open R',
    'renjin' = 'Renjin',
    'fastr' = 'FastR',
    'pqr' = 'pqR',
    'terr' = 'TERR'
)
```
There will be another function also to see if a combination is supported or not. 

I will need to fix the version also. Since there is probably different library support for different platform

> It is also great that you think about the mounting and the working directory. IMO the option you present above should suffice for your thesis. Don't worry about data outside of the current working directory! That really seems to be an edge case. Instead, in your own code, always use here::here(..) to load data relative to the current project, and you should be fine.

Ah ok, never use `here::here()` before. I will focus on running the script for now then.

> Next, think about the returned output. The output needs a reasonable data structure (something list-like) to access the results of list_of_impls * list_of_platform-many container runs!

Yes, a dictionary with a key from combination between implementation and platform would be ideal for this case.
```
result = all_result['gnur']['ubuntu']
```

> I strongly suggest you put your functions in a little R package. It just makes things a lot easier to develop for yourself, and easier for others to try out (clean dependency management, versioning, documentation, etc.). pkgKitten::kitten("..") might help you get started. My package name suggestion: altRnative smile

Yes, I agree, creating the package will make the project more useful for others. I will made one. I like your name suggestion `altRnative` :)

**Comment by ismailsunni** [comment]
ah I missed this one:
```
rhub::platforms()$name
```

I checked it and there are a lot and more variant

```
> rhub::platforms()$name
 [1] "debian-clang-devel"            "debian-gcc-devel"              "debian-gcc-devel-nold"        
 [4] "debian-gcc-patched"            "debian-gcc-release"            "fedora-clang-devel"           
 [7] "fedora-gcc-devel"              "linux-x86_64-centos6-epel"     "linux-x86_64-centos6-epel-rdt"
[10] "linux-x86_64-rocker-gcc-san"   "macos-elcapitan-release"       "solaris-x86-patched"          
[13] "ubuntu-gcc-devel"              "ubuntu-gcc-release"            "ubuntu-rchk"                  
[16] "windows-x86_64-devel"          "windows-x86_64-devel-rtools4"  "windows-x86_64-oldrel"        
[19] "windows-x86_64-patched"        "windows-x86_64-release"     
```

I will still need to mark which is supported and which one is not. So, having `altrnative::platforms()` probably better in this case.

**Comment by nuest** [comment]
Re. the returned output: maybe you can make the value a tidy tibble/data.frame? I think that is more useful than having nested objects:

```R
> library("tibble")
> tibble(dist = c("debian", "fedora", "fedora"), R = c("base", "base", "fastr"), output = list(list("works"), list("works not"), list("works almost")))
# A tibble: 3 x 3
  dist   R     output    
  <chr>  <chr> <list>    
1 debian base  <list [1]>
2 fedora base  <list [1]>
3 fedora fastr <list [1]>
```

See https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html

**Comment by ismailsunni** [comment]
Hi @nuest 
I am starting to work on the package on this repo https://github.com/ismailsunni/altRnative/
Still early.

Do you have a suggestion on how to run the code from the stevedore? I can't do it with `expression` properly for more than one `expression`. It will always only run the first code. See it here: https://github.com/ismailsunni/altRnative/blob/master/R/run.R#L12

Thanks.

It is still early stage, and I will work step by step.
